// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Authority.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::roomsec::interface;

class AuthorityHandler : virtual public AuthorityIf {
 public:
  AuthorityHandler() {
    // Your initialization goes here
  }

  void checkRequirements(std::vector<CredentialSpec> & _return, const std::string& resource) {
    // Your implementation goes here
    printf("checkRequirements\n");
  }

  AuthorizationReply::type authorize(const AuthorizationRequest& request) {
    // Your implementation goes here
    printf("authorize\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<AuthorityHandler> handler(new AuthorityHandler());
  shared_ptr<TProcessor> processor(new AuthorityProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

