/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef authorize_CONSTANTS_H
#define authorize_CONSTANTS_H

#include "authorize_types.h"

namespace roomsec { namespace interface {

class authorizeConstants {
 public:
  authorizeConstants();

};

extern const authorizeConstants g_authorize_constants;

}} // namespace

#endif
